typography_spectrum: 0.59319
color:
  saturation: 0.9426523
  brandStrength: 0.9860964
  lightness: 0.5663083
  brandColors:
    - '#503E88'
    - '#000000'
    - '#322755'
    - '#141022'
    - '#41336E'
  rhythmicContrast: 0.8530466
layout_spectrum: 0.3709677
name: Pauline Leale
navigation:
  - name: About Pauline
    id: 70d9fc05-8578-471a-99e7-f522ed99a4f0
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: International Property
description: Bespoke Buying Services
